# Setup and configure ruby things for reddit app
- name: "Reddit App: Configure app environment"
  hosts: all
  gather_facts: no
  become: yes

  tasks:
  - name: Install ruby and rubygems and required packages
    apt: "name={{ item }} state=present"
    with_items:
      - ruby-full
      - ruby-dev
      - build-essential

  - name: Install Ruby bundler
    gem:
      name: bundler
      state: present
      user_install: no

# Setup and configure mongodb for reddit app
- name: "Reddit App: Install mongodb"
  hosts: all
  gather_facts: no
   
  tasks:
  - name: Install keys
    apt_key:
       keyserver: hkp://keyserver.ubuntu.com:80
       id: EA312927
    sudo: yes
  
  - name: Install mongodb repo
    apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        filename: mongodb-org-3.2
    sudo: yes
       
  - name: Install mongodb package
    apt:
        name: mongodb-org
        update_cache: yes
    sudo: yes

  - name: Enable and start mongodb service
    service:
      name: mongod
      enabled: yes
      state: started
    sudo: yes
            

# Deploy reddit app
- name: "Reddit App: Deploy application"
  hosts: reddit_app
  gather_facts: no

  tasks:
  - name: Clone repo
    git:
      repo: 'https://github.com/Artemmkin/reddit.git'
      dest: '/home/appuser/reddit'
      clone: yes
      update: no

  - name: Bundler install
    bundler:
      chdir: '/home/appuser/reddit'
      state: latest

  - name: Copy .service file
    copy:
      src: '/home/temox/infra/ansible/files/puma.service'
      dest: '/etc/systemd/system/puma.service'
    sudo: yes

  - name: Enable and start puma service
    service:
      name: puma.service
      enabled: yes
      state: started
    sudo: yes
